---
- name: Configure infrastructure
  hosts: all
  roles:
    - { role: common, tags: [ common ] }
    - { role: docker, tags: [ docker ] }

- name: Bootstrap Kubernetes cluster
  hosts: masters
  roles:
    - { role: k8s_setup, tags: [ k8s_setup ] }

- name: Deploy MLOps app
  hosts: masters
  roles:
    - { role: mlops_app, tags: [ mlops_app ] }