---
- name: Configure infrastructure and deploy MLOps app
  hosts: all
  roles:
    - common
    - docker

- name: Bootstrap Kubernetes cluster and deploy app
  hosts: masters
  roles:
    - k8s_setup
    - mlops_app