apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-demo
  template:
    metadata:
      labels:
        app: mlops-demo
    spec:
      containers:
        - name: mlops-demo
          image: youruser/mlops-demo:${IMAGE_TAG}
          ports:
            - containerPort: 5000