apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: mlops-demo
    spec:
      containers:
        - name: mlops-demo
          image: sakshya4/mlops-demo:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi