apiVersion: v1
kind: Service
metadata:
  name: mlops-demo
  namespace: default
spec:
  type: NodePort
  selector:
    app: mlops-demo
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080