---
# tasks file for roles/mlops_app
- name: Copy application code
  copy:
    src: "{{ playbook_dir }}/app/"
    dest: /opt/mlops/app/
    mode: '0755'

- name: Ensure python3-pip is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
  become: true

- name: Install Kubernetes Python client libraries
  ansible.builtin.pip:
    name:
      - kubernetes
      - openshift
    state: present
  become: true

- name: Deploy Deployment manifest
  kubernetes.core.k8s:
    state: present
    src: "{{ playbook_dir }}/kubernetes/deployment.yaml"
  become: true

- name: Deploy Service manifest
  kubernetes.core.k8s:
    state: present
    src: "{{ playbook_dir }}/kubernetes/service.yaml"
  become: true

- name: Deploy HPA manifest
  kubernetes.core.k8s:
    state: present
    src: "{{ playbook_dir }}/kubernetes/hpa.yaml"
  become: true