---
# tasks file for roles/mlops_app
- name: Copy application code
  copy:
    src: "{{ playbook_dir }}/app/"
    dest: /opt/mlops/app/
    mode: '0755'

- name: Ensure python3-pip is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install Kubernetes Python client libraries
  ansible.builtin.pip:
    name:
      - kubernetes
      - openshift
    state: present

- name: Deploy Kubernetes manifests via kubectl
  ansible.builtin.command: kubectl apply -f {{ item }}
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  become: true
  loop:
    - "{{ playbook_dir }}/kubernetes/deployment.yaml"
    - "{{ playbook_dir }}/kubernetes/service.yaml"
    - "{{ playbook_dir }}/kubernetes/hpa.yaml"
  changed_when: true