---
# roles/mlops_app/tasks/main.yml

# 1. Ensure the application directory exists
- name: Ensure /opt/mlops/app directory exists
  ansible.builtin.file:
    path: /opt/mlops/app
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

# 2. Copy your ML app code
- name: Copy application code
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/app/"
    dest: /opt/mlops/app/
    mode: '0755'
  become: true

# 3. Install Python tooling
- name: Ensure python3-pip is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes
  become: true

- name: Install Kubernetes Python client libraries
  ansible.builtin.pip:
    name:
      - kubernetes
      - openshift
    state: present
  become: true

# 4. Deploy Kubernetes manifests using the same KUBECONFIG
- name: Deploy ML Ops app manifests to Kubernetes
  kubernetes.core.k8s:
    kubeconfig: "{{ lookup('env','KUBECONFIG') }}"
    state: present
    src: "{{ item }}"
  loop:
    - "{{ playbook_dir }}/kubernetes/deployment.yaml"
    - "{{ playbook_dir }}/kubernetes/service.yaml"
    - "{{ playbook_dir }}/kubernetes/hpa.yaml"
  become: false