---
# tasks file for roles/k8s_setup
- name: Ensure /etc/kubernetes directory is world-traversable
  ansible.builtin.file:
    path: /etc/kubernetes
    state: directory
    mode: '0755'
  become: true

- name: Ensure admin.conf is world-readable
  ansible.builtin.file:
    path: /etc/kubernetes/admin.conf
    state: file
    mode: '0644'
  become: true

- name: Add Kubernetes apt key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: true

- name: Download Kubernetes public signing key
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
    state: present
    keyring: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
  become: true

- name: Add Kubernetes community-owned apt repo
  ansible.builtin.apt_repository:
    filename: kubernetes
    repo: >
      deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg]
      https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install Kubernetes components
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: false

- name: Reset any existing Kubernetes cluster
  ansible.builtin.command: kubeadm reset -f
  ignore_errors: true
  become: true

- name: Remove stale manifests directory
  ansible.builtin.file:
    path: /etc/kubernetes/manifests
    state: absent
  become: true

- name: Remove leftover etcd data
  ansible.builtin.file:
    path: /var/lib/etcd
    state: absent
  become: true

- name: Remove old CNI configs
  ansible.builtin.file:
    path: /etc/cni/net.d
    state: absent
  become: true

- name: Initialize Kubernetes control-plane
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  when: inventory_hostname in groups['masters']
  become: true

- name: Ensure /root/.kube directory exists
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: '0700'
  become: true

- name: Copy kubeconfig for root
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
  when: inventory_hostname in groups['masters']
  become: true
