---
# roles/k8s_setup/tasks/main.yml

# 1. Add the Kubernetes apt key & repo, then install kubelet, kubeadm, kubectl
- name: Add Google Cloud apt key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: true

- name: Add Kubernetes public signing key
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
    state: present
    keyring: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
  become: true

- name: Add Kubernetes apt repository
  ansible.builtin.apt_repository:
    filename: kubernetes
    repo: >
      deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg]
      https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /
  become: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install kubelet, kubeadm, kubectl
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
  become: true

# 2. Detect whether the control-plane has already been initialized
- name: Check for existing admin.conf
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: admin_conf
  become: true

- name: Check cluster health if admin.conf exists
  ansible.builtin.command: kubectl get nodes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: cluster_status
  ignore_errors: true
  changed_when: false
  when: admin_conf.stat.exists
  become: true

# 3. Initialize control-plane only if missing or unhealthy
- name: Initialize Kubernetes control plane
  ansible.builtin.command: kubeadm init --pod-network-cidr=10.244.0.0/16
  when:
    - not admin_conf.stat.exists
    - inventory_hostname in groups['masters']
  register: kubeadm_init
  become: true

# 4. Configure kubectl for the root user on the master
- name: Ensure root .kube directory exists
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: '0700'
  when: kubeadm_init is changed
  become: true

- name: Copy admin.conf to root kubeconfig
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    owner: root
    mode: '0644'
  when: kubeadm_init is changed
  become: true

# 5. Deploy Calico CNI and Metrics Server on first init
- name: Deploy Calico network plugin
  ansible.builtin.command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: kubeadm_init is changed
  become: true
  changed_when: true

- name: Install Kubernetes Metrics Server
  ansible.builtin.command: kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: kubeadm_init is changed
  become: true
  changed_when: true

- name: Wait for Metrics Server to be ready
  ansible.builtin.command: >
    kubectl wait --for=condition=available
    deployment/metrics-server -n kube-system --timeout=120s
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: kubeadm_init is changed
  become: true
  changed_when: false
  ignore_errors: true