---
# tasks file for roles/docker

- name: Update apt package cache
  apt:
    update_cache: true
  become: true
  throttle: 1

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Add user to docker group
  user:
    name: "{{ ansible_user | default(ansible_env.USER) }}"
    groups: docker
    append: yes
  become: true